### ISSUE TITLE
Set back the previous emoji status (on reset)

### ISSUE THREAD

**Issue by Divi** [yakshaG/google-meet-slack-integration#5]
First issue 🎉 

Hello!

I have a (custom) emoji as a status when I'm not in a meeting and when the extension resets my status, my previous emoji is reset too 😞 
It should be great if the extension can get user status before setting the new one, then set the status in cache and reset the status with the stored cached status when leaving a meeting.

Btw, what a great extension 😱 💪🏻 Thanks for it!

**Comment by yakshaG** [comment]
Hello @Divi!

First of all, thanks for taking the time to share feedback! We are pumped to see that the extension is useful to you!! :smile: 

The feature you have suggested is definitely a great thing to add. @aditya-67  and I are already on it and we will update the extension soon. We are also fixing some other bugs in parallel and we will roll all of these together, in the next update.

We will notify you on this thread — stay tuned! :rocket:

**Comment by Divi** [comment]
Nice! Can't wait to see the update!

Thank you & @aditya-67 🙏🏻

**Comment by aditya-67** [comment]
@Divi, closing this wrt the comment made in issue #6

https://github.com/yakshaG/google-meet-slack-integration/issues/6#issuecomment-1208169361
